- name: create ec2 and r53 records
  hosts: localhost
  vars:
    zone: surisetty.online
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      name: "{{ item }}"
      security_group: allow-all
      image_id: ami-090252cbe067a9e58
      tags:
        Name: "{{ item }}"
    loop:
    - db
    - backend
    - frontend
    register: ec2_instance_info

  # - name:  create r53 records
  #   amazon.aws.route53:
  #   record: